select * from (
/*Test Instance without Run Status*/
SELECT
CASE WHEN CF_ITEM_NAME is null THEN (SELECT replace(min(CF_ITEM_PATH),'AAA','XXX')+'111222' FROM CYCL_FOLD where CF_FATHER_ID<>-1) ELSE CF_ITEM_PATH+'111222' END As 'Hierarchy',
CASE WHEN CF_ITEM_NAME is null THEN (SELECT replace(min(CF_ITEM_PATH),'AAA','XXX')+CAST(CY_CYCLE_ID AS VARCHAR(255)) FROM CYCL_FOLD where CF_FATHER_ID<>-1) ELSE CF_ITEM_PATH+CAST(CY_CYCLE_ID AS VARCHAR(255)) END As 'HierarchyOrder',
'['+CAST(TC_TEST_INSTANCE AS VARCHAR(255))+']'+(SELECT TS_NAME FROM TEST /*Test*/ WHERE TS_TEST_ID=TC_TEST_ID) As 'StructuralName',
/*CF_ITEM_ID,*/
/*CASE WHEN CF_ITEM_NAME is null THEN 'Unattached' ELSE CF_ITEM_NAME END As 'CF_ITEM_NAME',*/
/*CF_FATHER_ID, */
/*CF_ATTACHMENT,*/
CF_DESCR,
CY_CYCLE_ID,
CY_CYCLE,
CY_OPEN_DATE,
CY_CLOSE_DATE,
CY_STATUS,
CY_DESCRIPTION,
CY_COMMENT,
CY_ATTACHMENT,
/* CY_EXEC_EVENT_HANDLE, */
/* CY_ORDER_ID, */
/* CY_SUBTYPE_ID, */
/* TC_TESTCYCL_ID, */
TC_TEST_ID,
/* TC_TEST_CONFIG_ID, */
TC_TEST_ORDER,
TC_STATUS,
TC_TESTER_NAME,
TC_EXEC_DATE,
TC_EXEC_TIME,
TC_ATTACHMENT,
CASE WHEN TC_ITERATIONS is not null Then TC_ITERATIONS ELSE TC_USER_01 END As 'Defect ID',
/* TC_EXEC_EVENT_HANDLE, */
/* TC_TEST_INSTANCE,*/
/* TC_ACTUAL_TESTER, */
/* TC_ITERATIONS,*/
TC_SUBTYPE_ID,
/* TC_IS_DYNAMIC, */
TC_USER_25 AS 'Execution Comments',
RN_TEST_CONFIG_ID,
RN_RUN_ID,
/*RN_RUN_NAME,*/
RN_EXECUTION_DATE,
RN_EXECUTION_TIME,
RN_HOST,
RN_STATUS,
RN_DURATION,
RN_DRAFT,
RN_ATTACHMENT,
/* RN_TEST_INSTANCE, */
RN_OS_NAME,
RN_OS_SP,
RN_OS_BUILD,
RN_SUBTYPE_ID,
'' AS 'RCR_ID',
/*'' AS 'RCR_CRITERION_ID',*/
/*'' AS 'RCR_CONFIGURATION_ID',*/
/*'' AS 'RCR_NAME',*/
'' AS 'Configuration Description',
'' AS 'ST_ID',
'' AS 'ST_STEP_NAME',
'' AS 'ST_DESCRIPTION',
'' AS 'ST_EXPECTED',
'' AS 'ST_ACTUAL',
'' AS 'ST_EXECUTION_DATE',
'' AS 'ST_EXECUTION_TIME',
'' AS 'ST_STATUS',
'' AS 'ST_DESSTEP_ID',
'' AS 'ST_ATTACHMENT',
/*'' AS 'ST_REL_OBJ_ID',*/
'TSInstanceWithoutRun'As 'SectionType'
FROM CYCL_FOLD /*Test Set Folder (CYCLE)*/
right join CYCLE /*Test Set*/
on CYCL_FOLD.CF_ITEM_ID= CYCLE.CY_FOLDER_ID
right join TESTCYCL /*Test Instance*/
on CYCLE.CY_CYCLE_ID=TESTCYCL.TC_CYCLE_ID
left join RUN /*Run*/
on TESTCYCL.TC_TESTCYCL_ID=RUN.RN_TESTCYCL_ID
where  RN_TESTCYCL_ID is null

union
/*Test Instance with Run Status*/
SELECT
CASE WHEN CF_ITEM_NAME is null THEN (SELECT replace(min(CF_ITEM_PATH),'AAA','XXX')+'111222' FROM CYCL_FOLD where CF_FATHER_ID<>-1) ELSE CF_ITEM_PATH++'111222' END As 'Hierarchy',
CASE WHEN CF_ITEM_NAME is null THEN (SELECT replace(min(CF_ITEM_PATH),'AAA','XXX')+CAST(CY_CYCLE_ID AS VARCHAR(255)) FROM CYCL_FOLD where CF_FATHER_ID<>-1) ELSE CF_ITEM_PATH+CAST(CY_CYCLE_ID AS VARCHAR(255)) END As 'HierarchyOrder',
'['+CAST(TC_TEST_INSTANCE AS VARCHAR(255))+']'+(SELECT TS_NAME FROM TEST /*Test*/ WHERE TS_TEST_ID=TC_TEST_ID) As 'StructuralName',
/*CF_ITEM_ID,*/
/*CASE WHEN CF_ITEM_NAME is null THEN 'Unattached' ELSE CF_ITEM_NAME END As 'CF_ITEM_NAME',*/
/*CF_FATHER_ID, */
/*CF_ATTACHMENT,*/
CF_DESCR,
CY_CYCLE_ID,
CY_CYCLE,
CY_OPEN_DATE,
CY_CLOSE_DATE,
CY_STATUS,
CY_DESCRIPTION,
CY_COMMENT,
CY_ATTACHMENT,
/* CY_EXEC_EVENT_HANDLE, */
/* CY_ORDER_ID, */
/* CY_SUBTYPE_ID, */
/* TC_TESTCYCL_ID, */
TC_TEST_ID,
/* TC_TEST_CONFIG_ID, */
TC_TEST_ORDER,
TC_STATUS,
TC_TESTER_NAME,
TC_EXEC_DATE,
TC_EXEC_TIME,
TC_ATTACHMENT,
CASE WHEN TC_ITERATIONS is not null Then TC_ITERATIONS ELSE TC_USER_01 END As 'Defect ID',
/* TC_EXEC_EVENT_HANDLE, */
/* TC_TEST_INSTANCE,*/
/* TC_ACTUAL_TESTER, */
/* TC_ITERATIONS, */
TC_SUBTYPE_ID,
/* TC_IS_DYNAMIC, */
TC_USER_25 AS 'Execution Comments',
r.RN_TEST_CONFIG_ID,
r.RN_RUN_ID,
/*r.RN_RUN_NAME,*/
r.RN_EXECUTION_DATE,
r.RN_EXECUTION_TIME,
r.RN_HOST,
r.RN_STATUS,
r.RN_DURATION,
r.RN_DRAFT,
r.RN_ATTACHMENT,
/* r.RN_TEST_INSTANCE, */
r.RN_OS_NAME,
r.RN_OS_SP,
r.RN_OS_BUILD,
r.RN_SUBTYPE_ID,
RCR_ID,
/*RCR_CRITERION_ID,*/
/*RCR_CONFIGURATION_ID,*/
/*RCR_NAME,*/
RCR_DESCRIPTION As 'Configuration Description',
ST_ID,
ST_STEP_NAME,
ST_DESCRIPTION,
ST_EXPECTED,
ST_ACTUAL,
ST_EXECUTION_DATE,ST_EXECUTION_TIME,
ST_STATUS,
ST_DESSTEP_ID,
ST_ATTACHMENT,
/*ST_REL_OBJ_ID,*/
'TSInstanceWitRun'As 'SectionType'
FROM CYCL_FOLD /*Test Set Folder (CYCLE)*/
right join CYCLE /*Test Set*/
on CYCL_FOLD.CF_ITEM_ID= CYCLE.CY_FOLDER_ID
right join TESTCYCL /*Test Instance*/
on CYCLE.CY_CYCLE_ID=TESTCYCL.TC_CYCLE_ID
right join RUN /*Run*/r
INNER JOIN (
    SELECT RN_TESTCYCL_ID,RN_CYCLE_ID,RN_TEST_ID,RN_TEST_CONFIG_ID, MAX(RN_VTS) as latest
    FROM RUN
    GROUP BY RN_TESTCYCL_ID,RN_CYCLE_ID,RN_TEST_ID,RN_TEST_CONFIG_ID
) as latest_records ON r.RN_TESTCYCL_ID = latest_records.RN_TESTCYCL_ID AND r.RN_CYCLE_ID = latest_records.RN_CYCLE_ID AND r.RN_TEST_ID = latest_records.RN_TEST_ID AND r.RN_TEST_CONFIG_ID=latest_records.RN_TEST_CONFIG_ID AND r.RN_VTS = latest_records.latest
on TESTCYCL.TC_TESTCYCL_ID=r.RN_TESTCYCL_ID
right join RUN_CRITERIA /*Run Criteria*/
on r.RN_RUN_ID=RUN_CRITERIA.RCR_RUN_ID
right join STEP /*Test Step*/
on r.RN_RUN_ID=STEP.ST_RUN_ID
where (SELECT TS_NAME FROM TEST /*Test*/ WHERE TS_TEST_ID=TC_TEST_ID) is not null
union
/*test set*/
SELECT
CASE WHEN CF_ITEM_NAME is null THEN (SELECT replace(min(CF_ITEM_PATH),'AAA','XXX')+'111' FROM CYCL_FOLD where CF_FATHER_ID<>-1) ELSE CF_ITEM_PATH+'111' END As 'Hierarchy',
CASE WHEN CF_ITEM_NAME is null THEN (SELECT replace(min(CF_ITEM_PATH),'AAA','XXX')+CAST(CY_CYCLE_ID AS VARCHAR(255)) FROM CYCL_FOLD where CF_FATHER_ID<>-1) ELSE CF_ITEM_PATH+CAST(CY_CYCLE_ID AS VARCHAR(255)) END As 'HierarchyOrder',
CY_CYCLE As 'StructuralName',
/*CF_ITEM_ID,*/
/*CASE WHEN CF_ITEM_NAME is null THEN 'Unattached' ELSE CF_ITEM_NAME END As 'CF_ITEM_NAME',*/
/*CF_FATHER_ID, */
/*CF_ATTACHMENT,*/
CF_DESCR,
CY_CYCLE_ID,
CY_CYCLE,
CY_OPEN_DATE,
CY_CLOSE_DATE,
CY_STATUS,
CY_DESCRIPTION,
CY_COMMENT,
CY_ATTACHMENT,
/* CY_EXEC_EVENT_HANDLE, */
/* CY_ORDER_ID, */
/* CY_SUBTYPE_ID, */
/* '' AS 'TC_TESTCYCL_ID', */
'' AS 'TC_TEST_ID',
/* '' AS 'TC_TEST_CONFIG_ID', */
'' AS 'TC_TEST_ORDER',
'' AS 'TC_STATUS',
'' AS 'TC_TESTER_NAME',
'' AS 'TC_EXEC_DATE',
'' AS 'TC_EXEC_TIME',
'' AS 'TC_ATTACHMENT',
'' AS 'Defect ID' /*'TC_USER_01'*/,
/* '' AS 'TC_EXEC_EVENT_HANDLE',*/
/* '' AS 'TC_TEST_INSTANCE', */
/* '' AS 'TC_ACTUAL_TESTER', */
/* '' AS 'TC_ITERATIONS', */
'' AS 'TC_SUBTYPE_ID',
/* '' AS 'TC_IS_DYNAMIC', */
'' AS 'Execution Comments' /*'TC_USER_25'*/ ,
'' AS 'RN_TEST_CONFIG_ID',
'' AS 'RN_RUN_ID',
/*'' AS 'RN_RUN_NAME',*/
'' AS 'RN_EXECUTION_DATE',
'' AS 'RN_EXECUTION_TIME',
'' AS 'RN_HOST',
'' AS 'RN_STATUS',
'' AS 'RN_DURATION',
'' AS 'RN_DRAFT',
'' AS 'RN_ATTACHMENT',
/*'' AS 'RN_TEST_INSTANCE',*/
'' AS 'RN_OS_NAME',
'' AS 'RN_OS_SP',
'' AS 'RN_OS_BUILD',
'' AS 'RN_SUBTYPE_ID',
'' AS 'RCR_ID',
/*'' AS 'RCR_CRITERION_ID',*/
/*'' AS 'RCR_CONFIGURATION_ID',*/
/*'' AS 'RCR_NAME',*/
'' AS 'Configuration Description',
'' AS 'ST_ID',
'' AS 'ST_STEP_NAME',
'' AS 'ST_DESCRIPTION',
'' AS 'ST_EXPECTED',
'' AS 'ST_ACTUAL',
'' AS 'ST_EXECUTION_DATE',
'' AS 'ST_EXECUTION_TIME',
'' AS 'ST_STATUS',
'' AS 'ST_DESSTEP_ID',
'' AS 'ST_ATTACHMENT',
/*'' AS 'ST_REL_OBJ_ID',*/
'TestSet'As 'SectionType'
FROM CYCL_FOLD /*Test Set Folder (CYCLE)*/
right join CYCLE /*Test Set*/
on CYCL_FOLD.CF_ITEM_ID= CYCLE.CY_FOLDER_ID
union
/*folder structor*/
SELECT
CF_ITEM_PATH As 'Hierarchy',
CF_ITEM_PATH As 'HierarchyOrder',
CASE WHEN CF_ITEM_NAME is null THEN 'Unattached' ELSE CF_ITEM_NAME END As 'StructuralName',
/*CF_ITEM_ID,*/
/*CASE WHEN CF_ITEM_NAME is null THEN 'Unattached' ELSE CF_ITEM_NAME END As 'CF_ITEM_NAME',*/
/*CF_FATHER_ID, */
/*CF_ATTACHMENT,*/
CF_DESCR,
'' AS 'CY_CYCLE_ID',
'' AS 'CY_CYCLE',
'' AS 'CY_OPEN_DATE',
'' AS 'CY_CLOSE_DATE',
'' AS 'CY_STATUS',
'' AS 'CY_DESCRIPTION',
'' AS 'CY_COMMENT',
'' AS 'CY_ATTACHMENT',
/* '' AS 'CY_EXEC_EVENT_HANDLE', */
/* '' AS 'CY_ORDER_ID',*/
/* '' AS 'CY_SUBTYPE_ID', */
/* '' AS 'TC_TESTCYCL_ID', */
'' AS 'TC_TEST_ID',
/* '' AS 'TC_TEST_CONFIG_ID', */
'' AS 'TC_TEST_ORDER',
'' AS 'TC_STATUS',
'' AS 'TC_TESTER_NAME',
'' AS 'TC_EXEC_DATE',
'' AS 'TC_EXEC_TIME',
'' AS 'TC_ATTACHMENT',
'' AS 'Defect ID' /*'TC_USER_01'*/,
/* '' AS 'TC_EXEC_EVENT_HANDLE', */
/* '' AS 'TC_TEST_INSTANCE', */
/* '' AS 'TC_ACTUAL_TESTER', */
/* '' AS 'TC_ITERATIONS', */
'' AS 'TC_SUBTYPE_ID',
/* '' AS 'TC_IS_DYNAMIC', */
'' AS 'Execution Comments' /*'TC_USER_25'*/ ,
'' AS 'RN_TEST_CONFIG_ID',
'' AS 'RN_RUN_ID',
/*'' AS 'RN_RUN_NAME',*/
'' AS 'RN_EXECUTION_DATE',
'' AS 'RN_EXECUTION_TIME',
'' AS 'RN_HOST',
'' AS 'RN_STATUS',
'' AS 'RN_DURATION',
'' AS 'RN_DRAFT',
'' AS 'RN_ATTACHMENT',
/*'' AS 'RN_TEST_INSTANCE',*/
'' AS 'RN_OS_NAME',
'' AS 'RN_OS_SP',
'' AS 'RN_OS_BUILD',
'' AS 'RN_SUBTYPE_ID',
'' AS 'RCR_ID',
/*'' AS 'RCR_CRITERION_ID',*/
/*'' AS 'RCR_CONFIGURATION_ID',*/
/*'' AS 'RCR_NAME',*/
'' AS 'Configuration Description',
'' AS 'ST_ID',
'' AS 'ST_STEP_NAME',
'' AS 'ST_DESCRIPTION',
'' AS 'ST_EXPECTED',
'' AS 'ST_ACTUAL',
'' AS 'ST_EXECUTION_DATE',
'' AS 'ST_EXECUTION_TIME',
'' AS 'ST_STATUS',
'' AS 'ST_DESSTEP_ID',
'' AS 'ST_ATTACHMENT',
/*'' AS 'ST_REL_OBJ_ID',*/
'folderName' As 'SectionType'
FROM CYCL_FOLD /*Test Set Folder (CYCLE)*/
where CF_FATHER_ID<>-1
union
/*Unattached folder*/
SELECT
/*'' AS 'CF_ITEM_ID',*/
/*'Unattached' As 'CF_ITEM_NAME',*/
(SELECT replace(min(CF_ITEM_PATH),'AAA','XXX') FROM CYCL_FOLD where CF_FATHER_ID<>-1) As 'Hierarchy',
(SELECT replace(min(CF_ITEM_PATH),'AAA','XXX') FROM CYCL_FOLD where CF_FATHER_ID<>-1) As 'HierarchyOrder',
'Unattached' As 'StructuralName',
/*'' AS 'CF_FATHER_ID', */
/*'' AS 'CF_ATTACHMENT',*/
'' AS 'CF_DESCR',
'' AS 'CY_CYCLE_ID',
'' AS 'CY_CYCLE',
'' AS 'CY_OPEN_DATE',
'' AS 'CY_CLOSE_DATE',
'' AS 'CY_STATUS',
'' AS 'CY_DESCRIPTION',
'' AS 'CY_COMMENT',
'' AS 'CY_ATTACHMENT',
/* '' AS 'CY_EXEC_EVENT_HANDLE', */
/* '' AS 'CY_ORDER_ID', */
/* '' AS 'CY_SUBTYPE_ID', */
/* '' AS 'TC_TESTCYCL_ID', */
'' AS 'TC_TEST_ID',
/* '' AS 'TC_TEST_CONFIG_ID', */
'' AS 'TC_TEST_ORDER',
'' AS 'TC_STATUS',
'' AS 'TC_TESTER_NAME',
'' AS 'TC_EXEC_DATE',
'' AS 'TC_EXEC_TIME',
'' AS 'TC_ATTACHMENT',
'' AS 'Defect ID' /*'TC_USER_01'*/,
/* '' AS 'TC_EXEC_EVENT_HANDLE', */
/* '' AS 'TC_TEST_INSTANCE', */
/* '' AS 'TC_ACTUAL_TESTER', */
/* '' AS 'TC_ITERATIONS', */
'' AS 'TC_SUBTYPE_ID',
/* '' AS 'TC_IS_DYNAMIC', */
'' AS 'Execution Comments' /*'TC_USER_25'*/ ,
'' AS 'RN_TEST_CONFIG_ID',
'' AS 'RN_RUN_ID',
/*'' AS 'RN_RUN_NAME',*/
'' AS 'RN_EXECUTION_DATE',
'' AS 'RN_EXECUTION_TIME',
'' AS 'RN_HOST',
'' AS 'RN_STATUS',
'' AS 'RN_DURATION',
'' AS 'RN_DRAFT',
'' AS 'RN_ATTACHMENT',
/* '' AS 'RN_TEST_INSTANCE', */
'' AS 'RN_OS_NAME',
'' AS 'RN_OS_SP',
'' AS 'RN_OS_BUILD',
'' AS 'RN_SUBTYPE_ID',
'' AS 'RCR_ID',
/*'' AS 'RCR_CRITERION_ID',*/
/*'' AS 'RCR_CONFIGURATION_ID',*/
/*'' AS 'RCR_NAME',*/
'' AS 'Configuration Description',
'' AS 'ST_ID',
'' AS 'ST_STEP_NAME',
'' AS 'ST_DESCRIPTION',
'' AS 'ST_EXPECTED',
'' AS 'ST_ACTUAL',
'' AS 'ST_EXECUTION_DATE',
'' AS 'ST_EXECUTION_TIME',
'' AS 'ST_STATUS',
'' AS 'ST_DESSTEP_ID',
'' AS 'ST_ATTACHMENT',
/*'' AS 'ST_REL_OBJ_ID',*/
'Unattached folder'As 'SectionType'

) As A
where HierarchyOrder like 'AAAAAFAD%' or HierarchyOrder like 'AAAAAFAE%' or HierarchyOrder like 'AAAAAFAF%'
order by HierarchyOrder,TC_TEST_ORDER