SELECT
REQ_COVER.RC_REQ_ID As 'QC_ReqID',
(select RQ_REQ_NAME from REQ where REQ_COVER.RC_REQ_ID=REQ.RQ_REQ_ID) As 'QC_ReqName',
REQ_COVER.RC_ENTITY_ID As 'QC_TCID',
(SELECT TEST.TS_NAME FROM TEST where REQ_COVER.RC_ENTITY_ID=TEST.TS_TEST_ID) As 'QC_TCName'
FROM  REQ_COVER
order by RC_REQ_ID,RC_ENTITY_ID